### ISSUE TITLE
nacos 里面的配置文件内容

### ISSUE THREAD

**Issue by J-Orange** [xiaonannet/mqtts#5]
可以公开nacos配置中心的配置文件内容吗？

**Comment by xiaonannet** [comment]
打开mqtts根目录下的/doc/nacos-config，在nacos服务器中导入即可

**Comment by J-Orange** [comment]
> 打开mqtts根目录下的/doc/nacos-config，在nacos服务器中导入即可

谢谢，看到了。我看到sentinel配置的数据源是nacos，那nacos数据同步到sentinel这块也有做吗

**Comment by J-Orange** [comment]
> 打开mqtts根目录下的/doc/nacos-config，在nacos服务器中导入即可

谢谢，看到了。我看到sentinel配置的数据源是nacos，那nacos数据同步到sentinel这块也有做吗

**Comment by xiaonannet** [comment]
doc/nacos-config下的sentinel配置可以导入nacos配置文件中，具体的sentinel服务配置在gateway模块中，sentinel服务直接去官网下载最新版即可

**Comment by J-Orange** [comment]
> doc/nacos-config下的sentinel配置可以导入nacos配置文件中，具体的sentinel服务配置在gateway模块中，sentinel服务直接去官网下载最新版即可

请问项目的前端怎么启动啊?还有swagger的地址是哪个
